apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Aislamiento del namespace del sistema
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    pod-security.kubernetes.io/enforce: restricted